
###Librerias###

#Para no ocupar espacio en el resto de scripts y no repetirlas

library(readr)
library(readxl)
library(stats)
library(ISLR)
library(dplyr)
library(lubridate)
library(ggplot2)
library(prophet)
library(TSdata)
library(mosaic)
library(ZeBook)
library(tstools)
library(RSNNS)
library(neuralnet)
library(caret)
library(zoo)
library(tidyverse)
library(seasonal)
library(VIM)
library(corrplot)
library(hexbin)
library(modelr)
library(cowplot)
library(grid)
library(gridExtra)
library(openxlsx)
library(countrycode)
library(prophet)
library(TSA)
library(forecast)
require(deSolve)
library(spectral)
library(sf)
library(rgdal) 
library(broom) 
library(tidyverse)
library(stringr)
library(rgeos)
library(maps)
library(FNN)
library(tree)
library(rattle)
library(randomForest)
library(gbm)
library(gam)
library(akima)
library(GGally)

