
#Cambiamos nombres de paises en MercaBarna y MercaMadrid
#Asi podemos unir con datos de Covid
  
#Merca Barna
MercaBarna2 = MercaBarna %>% 
  mutate(REPORTER = as.character(REPORTER)) %>%
  mutate(REPORTER =  str_replace(REPORTER,"ALAVA","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"ALBACETE","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"ALEMANIA","German")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"ALICANTE","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"ALMERIA","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"ANDORRA","Andorr")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"ARGENTINA","Argent")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"AUSTRIA","Austri")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"AVILA","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"BADAJOZ","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"BALEARES","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"BARCELONA","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"BELGICA","Belgiu")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"BRASIL","Brazil")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"BURGOS","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"CACERES","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"CADIZ","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"CAMERUN","Camero")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"CANADA","Canada")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"CATELLON","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"CHILE","Chile")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"CHINA","China")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"CIUDAD REAL","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"COLOMBIA","Colomb")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"CORDOBA","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"COREA","Korea")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"COSTA MARFIL","Ivory")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"COSTA RICA","Costa Rica")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"CUBA","Cuba")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"CUENCA","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"DINAMARCA","Denmar")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"ECUADOR","Ecuado")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"FRANCIA","France")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"GERONA","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"GRAN BRETAÑA","Britai")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"GRANADA","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"GRECIA","Greece")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"GUADALAJARA","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"GUIPUZCOA","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"HOLANDA","Hollan")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"HUELVA","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"HUESCA","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"IRLANDA","Irelan")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"ISLANDIA","Icelan")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"ISRAEL","Israel")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"ITALIA","Italy")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"JAEN","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"KENIA","Kenya")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"LA CORUÑA","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"LAS PALMAS","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"LEON","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"LERIDA","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"LOGROÑO","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"LUGO","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"LUXXEMBURGO","Luxemb")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"MADRID","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"MALAGA","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"MARRUECOS","Morocc")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"MEJICO","Mexico")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"MURCIA","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"NAVARRA","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"NUEVA ZELANDA","New_Ze")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"OCEANIA","Oceani")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"ORENSE","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"OTRAS PROVINCIAS","Other Provinces")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"OTROS AFRICA","Other Africa")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"OTROS AMERICA","Other America")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"OTROS ASIA","Other Asia")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"OTROS ESPAÑA","Other Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"OTROS EUROPA","Other Europe")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"OVIEDO","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"PALENCIA","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"PONTEVEDRA","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"PORTUGAL","Portug")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"SALAMANCA","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"SANTANDER","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"SEGOVIA","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"SEVILLA","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"SORIA","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"SUDAFRICA","South_")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"SUECIA","Sweden")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"SUIZA","Switze")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"TAILANDIA","Thaila")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"TARRAGONA","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"TENERIFE","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"TERUEL","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"TOLEDO","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"TUNEZ","Tunisi")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"TURQUIA","Turkey")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"URUGUAY","Urugua")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"USA","USA")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"VALENCIA","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"VALLADOLID","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"VIZCAYA","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"ZAMORA","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"ZARAGOZA","Spain"))%>%
  arrange(REPORTER,PRODUCT,YEAR,MONTH)

#MercaMadrid

MercaMadrid2 = MercaMadrid %>%
  mutate(REPORTER = as.character(REPORTER)) %>%
  mutate(REPORTER =  str_replace(REPORTER,"ALAVA","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"ALBACETE","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"ALEMANIA","German")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"ALICANTE","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"ALMERIA","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"ANGOLA","Angola")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"ARGELIA","Argeli")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"ARGENTINA","Argent")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"ASTURIAS","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"AUSTRIA","Austri")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"AVILA","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"BADAJOZ","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"BALEARES","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"BARCELONA","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"BELGICA","Belgiu")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"BRASIL","Brazil")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"BULGARIA","Bulgar")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"BURGOS","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"CACERES","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"CADIZ","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"CAMERUN","Camero")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"CANADA","Canada")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"CANTABRIA","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"CASTELLON","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"CHILE","Chile")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"CHINA","China")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"CIUDAD REAL","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"COLOMBIA","Colomb")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"CORDOBA","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"COSTA DE MARFIL","Ivory Coast")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"COSTA RICA","Costa_")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"CUBA","Cuba")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"CUENCA","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"DINAMARCA","Denmar")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"ECUADOR","Ecuado")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"EGIPTO","Egypt")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"ESTADOS UNIDOS","United")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"FRANCIA","France")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"GERONA","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"GRAN BRETAÃA","Britai")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"GRANADA","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"GRECIA","Greece")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"GUADALAJARA","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"GUATEMALA","Guatem")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"GUIPUZCOA","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"HOLANDA","Hollan")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"HONDURAS","Hondur")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"HUELVA","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"HUESCA","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"INDIA","India")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"INDONESIA","Indone")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"IRLANDA","Irelan")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"ISRAEL","Israel")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"ITALIA","Italy")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"JAEN","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"KENIA","Kenya")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"LA CORUÃA","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"LA RIOJA","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"LAS PALMAS","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"LEON","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"LERIDA","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"LUGO","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"MADRID","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"MALAGA","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"MARRUECOS","Morocc")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"MEJICO","Mexico")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"MURCIA","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"NAVARRA","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"NUEVA ZELANDA","New_Ze")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"ORENSE","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"OTROS P.SUDAMERICANO","Other SouthAmerica")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"OTROS PAIS. EUROPEOS","Other Europe")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"OTROS PAIS.AFRICANOS","Other Africa")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"OTROS PAIS.ASIATICOS","Other Asia")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"PALENCIA","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"PANAMA","Panama")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"PERU","Peru")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"POLONIA","Poland")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"PONTEVEDRA","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"PORTUGAL","Portugal")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"REPUBLICA DOMINICANA","Domini")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"SALAMANCA","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"SEGOVIA","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"SENEGAL","Senega")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"SEVILLA","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"SORIA","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"STA.CRUZ DE TENERIFE","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"SUDAFRICA","South_")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"SUIZA","Switze")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"TÃNEZ","Tunisi")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"TAILANDIA","Thaila")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"TARRAGONA","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"TERUEL","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"TOLEDO","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"TURQUIA","Turkey")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"URUGUAY","Urugua")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"VALENCIA","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"VALLADOLID","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"VENEZUELA","Venezu")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"VIETNAM","Vietna")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"VIZCAYA","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"ZAMORA","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"ZARAGOZA","Spain"))

###############################################################################

#Analisis y resultados cambiar nombre MB_INDEX

#MB_INDEX
MB_INDEX = MB_INDEX %>% 
  mutate(REPORTER = as.character(REPORTER)) %>%
  mutate(REPORTER =  str_replace(REPORTER,"ALAVA","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"ALBACETE","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"ALEMANIA","German")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"ALICANTE","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"ALMERIA","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"ANDORRA","Andorr")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"ARGENTINA","Argent")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"AUSTRIA","Austri")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"AVILA","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"BADAJOZ","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"BALEARES","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"BARCELONA","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"BELGICA","Belgiu")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"BRASIL","Brazil")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"BURGOS","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"CACERES","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"CADIZ","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"CAMERUN","Camero")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"CANADA","Canada")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"CATELLON","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"CHILE","Chile")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"CHINA","China")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"CIUDAD REAL","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"COLOMBIA","Colomb")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"CORDOBA","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"COREA","Korea")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"COSTA MARFIL","Ivory")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"COSTA RICA","Costa Rica")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"CUBA","Cuba")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"CUENCA","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"DINAMARCA","Denmar")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"ECUADOR","Ecuado")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"FRANCIA","France")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"GERONA","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"GRAN BRETAÑA","Britai")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"GRANADA","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"GRECIA","Greece")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"GUADALAJARA","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"GUIPUZCOA","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"HOLANDA","Hollan")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"HUELVA","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"HUESCA","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"IRLANDA","Irelan")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"ISLANDIA","Icelan")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"ISRAEL","Israel")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"ITALIA","Italy")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"JAEN","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"KENIA","Kenya")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"LA CORUÑA","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"LAS PALMAS","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"LEON","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"LERIDA","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"LOGROÑO","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"LUGO","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"LUXXEMBURGO","Luxemb")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"MADRID","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"MALAGA","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"MARRUECOS","Morocc")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"MEJICO","Mexico")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"MURCIA","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"NAVARRA","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"NUEVA ZELANDA","New_Ze")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"OCEANIA","Oceani")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"ORENSE","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"OTRAS PROVINCIAS","Other Provinces")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"OTROS AFRICA","Other Africa")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"OTROS AMERICA","Other America")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"OTROS ASIA","Other Asia")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"OTROS ESPAÑA","Other Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"OTROS EUROPA","Other Europe")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"OVIEDO","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"PALENCIA","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"PONTEVEDRA","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"PORTUGAL","Portug")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"SALAMANCA","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"SANTANDER","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"SEGOVIA","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"SEVILLA","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"SORIA","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"SUDAFRICA","South_")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"SUECIA","Sweden")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"SUIZA","Switze")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"TAILANDIA","Thaila")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"TARRAGONA","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"TENERIFE","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"TERUEL","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"TOLEDO","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"TUNEZ","Tunisi")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"TURQUIA","Turkey")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"URUGUAY","Urugua")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"USA","USA")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"VALENCIA","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"VALLADOLID","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"VIZCAYA","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"ZAMORA","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"ZARAGOZA","Spain"))

#MM_INDEX
MM_INDEX = MM_INDEX %>% 
  mutate(REPORTER = as.character(REPORTER)) %>%
  mutate(REPORTER =  str_replace(REPORTER,"ALAVA","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"ALBACETE","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"ALEMANIA","German")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"ALICANTE","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"ALMERIA","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"ANDORRA","Andorr")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"ARGENTINA","Argent")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"AUSTRIA","Austri")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"AVILA","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"BADAJOZ","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"BALEARES","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"BARCELONA","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"BELGICA","Belgiu")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"BRASIL","Brazil")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"BURGOS","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"CACERES","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"CADIZ","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"CAMERUN","Camero")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"CANADA","Canada")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"CATELLON","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"CHILE","Chile")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"CHINA","China")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"CIUDAD REAL","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"COLOMBIA","Colomb")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"CORDOBA","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"COREA","Korea")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"COSTA MARFIL","Ivory")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"COSTA RICA","Costa Rica")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"CUBA","Cuba")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"CUENCA","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"DINAMARCA","Denmar")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"ECUADOR","Ecuado")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"FRANCIA","France")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"GERONA","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"GRAN BRETAÑA","Britai")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"GRANADA","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"GRECIA","Greece")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"GUADALAJARA","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"GUIPUZCOA","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"HOLANDA","Hollan")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"HUELVA","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"HUESCA","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"IRLANDA","Irelan")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"ISLANDIA","Icelan")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"ISRAEL","Israel")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"ITALIA","Italy")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"JAEN","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"KENIA","Kenya")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"LA CORUÑA","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"LAS PALMAS","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"LEON","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"LERIDA","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"LOGROÑO","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"LUGO","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"LUXXEMBURGO","Luxemb")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"MADRID","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"MALAGA","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"MARRUECOS","Morocc")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"MEJICO","Mexico")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"MURCIA","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"NAVARRA","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"NUEVA ZELANDA","New_Ze")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"OCEANIA","Oceani")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"ORENSE","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"OTRAS PROVINCIAS","Other Provinces")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"OTROS AFRICA","Other Africa")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"OTROS AMERICA","Other America")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"OTROS ASIA","Other Asia")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"OTROS ESPAÑA","Other Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"OTROS EUROPA","Other Europe")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"OVIEDO","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"PALENCIA","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"PONTEVEDRA","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"PORTUGAL","Portug")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"SALAMANCA","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"SANTANDER","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"SEGOVIA","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"SEVILLA","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"SORIA","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"SUDAFRICA","South_")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"SUECIA","Sweden")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"SUIZA","Switze")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"TAILANDIA","Thaila")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"TARRAGONA","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"TENERIFE","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"TERUEL","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"TOLEDO","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"TUNEZ","Tunisi")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"TURQUIA","Turkey")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"URUGUAY","Urugua")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"USA","USA")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"VALENCIA","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"VALLADOLID","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"VIZCAYA","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"ZAMORA","Spain")) %>%
  mutate(REPORTER =  str_replace(REPORTER,"ZARAGOZA","Spain"))

